global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'ms-inventario'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['ms-inventario:8082']

  - job_name: 'ms-pedidos'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['ms-pedidos:8083']

  - job_name: 'ms-notificaciones'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['ms-notificaciones:8084']

  - job_name: 'ms-auth'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['ms-auth:8085']

  - job_name: 'ms-entrega'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['ms-entrega:8086']

  - job_name: 'api-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['api-gateway:8080']

  - job_name: 'ms-proveedores'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['ms-proveedores:8087']

  - job_name: 'ms-reportes'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['ms-reportes:8088']
