spring.application.name=ms-auth
server.port=8085

# Base de datos
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/auth_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:marte}

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# JWT — clave secreta (mínimo 32 caracteres)
jwt.secret=madera-mineria-clave-secreta-2026-cibertec
jwt.expiration=86400000

# Actuator
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.observations.key-values.application=${spring.application.name}
