spring.application.name=eureka-server
server.port=8761

# No se registra a sí mismo
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Nombre del servidor en el dashboard web de Eureka Server
eureka.instance.hostname=localhost

# Dashboard web de Eureka Server
eureka.server.dashboard.enabled=true
eureka.server.enable-self-preservation=false